/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMenu: typeof import('./components/AppMenu.vue')['default']
    Card: typeof import('./components/taro/Card.vue')['default']
    ChatBubble: typeof import('./components/chat/ChatBubble.vue')['default']
    ChatHeader: typeof import('./components/chat/ChatHeader.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    ChatMessage: typeof import('./components/chat/ChatMessage.vue')['default']
    InfinityMessages: typeof import('./components/chat-room/InfinityMessages.vue')['default']
    MindMap: typeof import('./components/map/MindMap.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NFlex: typeof import('naive-ui')['NFlex']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMenuItem: typeof import('naive-ui')['NMenuItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NP: typeof import('naive-ui')['NP']
    NSpace: typeof import('naive-ui')['NSpace']
    NStatistic: typeof import('naive-ui')['NStatistic']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialMessage: typeof import('./components/social/SocialMessage.vue')['default']
    Statistic: typeof import('./components/social/Statistic.vue')['default']
    TaroCard: typeof import('./components/taro/TaroCard.vue')['default']
    TaroUser: typeof import('./components/chat/TaroUser.vue')['default']
    UserCard: typeof import('./components/chat/UserCard.vue')['default']
    UserChatMany: typeof import('./components/chat/UserChatMany.vue')['default']
    UserChatSingle: typeof import('./components/chat/UserChatSingle.vue')['default']
  }
}
